name: build

on:
  push:
    branches: 
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        platform: [x64, Win32]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure ${{matrix.platform}}
      shell: cmd
      run: cmake -G "Visual Studio 16 2019" -A ${{matrix.platform}} -S ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build ${{matrix.platform}}
      shell: cmd
      run: cmake --build ${{github.workspace}}/build --config %BUILD_TYPE%

    
